### ISSUE TITLE
no audio via hdmi(comes out of speaker) 

### ISSUE THREAD

**Issue by piklz** [kiteretro/Circuit-Sword#62] opened 2018-09-19 17:35 UTC
latest image used as of sep18 '18

**Comment by kiteretro** [comment] 2018-09-22 13:56
Thanks, this is a duplicate of #28 where i've added the 'audio over hdmi' bit to solve this :) i have a working version which is being tested, so not far off!

**Closed by kiteretro** 2018-09-22 13:56 UTC

**Comment by piklz** [comment] 2018-09-23 16:41
soz cheers!
